version: "3.7"

services:
  edtr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: edtr
    environment:
     - EDITOR_API_URL=http://api.edtr.l
     - SERVER_API_URL=api.schul-cloud.l
     - EDITOR_SOCKET_URL=ws://api.edtr.l
    ports:
      - 1234:80
    restart: unless-stopped
    command: env.sh